// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA47sxBSPmYFbBfSHL_8kAV8gLXyaaAqcI',
    appId: '1:817595942719:web:277bbaba813d37676e358a',
    messagingSenderId: '817595942719',
    projectId: 'foodin-93814',
    authDomain: 'foodin-93814.firebaseapp.com',
    storageBucket: 'foodin-93814.appspot.com',
    measurementId: 'G-D28YHW8HVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApIWF9UdhrVJZirlgh_WP5_Fk-J36qM7Y',
    appId: '1:817595942719:android:e39fec510e84d5b36e358a',
    messagingSenderId: '817595942719',
    projectId: 'foodin-93814',
    storageBucket: 'foodin-93814.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADBhhKTZSUdQCRh22gIySE5uYl9C9voYY',
    appId: '1:817595942719:ios:24519d57851ac92c6e358a',
    messagingSenderId: '817595942719',
    projectId: 'foodin-93814',
    storageBucket: 'foodin-93814.appspot.com',
    androidClientId: '817595942719-663u7pcmhotregkpnd3k9i2e9of08d4j.apps.googleusercontent.com',
    iosClientId: '817595942719-u5u7qeda4p6ko9qjii8ojn1l49qtgkms.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodinMerchant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADBhhKTZSUdQCRh22gIySE5uYl9C9voYY',
    appId: '1:817595942719:ios:24519d57851ac92c6e358a',
    messagingSenderId: '817595942719',
    projectId: 'foodin-93814',
    storageBucket: 'foodin-93814.appspot.com',
    androidClientId: '817595942719-663u7pcmhotregkpnd3k9i2e9of08d4j.apps.googleusercontent.com',
    iosClientId: '817595942719-u5u7qeda4p6ko9qjii8ojn1l49qtgkms.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodinMerchant',
  );
}
